apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: interview-prep
type: Opaque
stringData:
  POSTGRES_USER: grader
  POSTGRES_PASSWORD: graderpass
  POSTGRES_DB: examgrader
  DATABASE_URL: "postgresql://grader:graderpass@164.92.183.143:5432/examgrader"
